# Generated by Django 4.0.4 on 2022-05-21 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resid', models.BigIntegerField()),
                ('cuisine', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('cost', models.IntegerField()),
                ('currency', models.CharField(max_length=25)),
                ('book', models.CharField(max_length=5)),
                ('delivery', models.CharField(max_length=5)),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('link', models.CharField(max_length=50)),
            ],
        ),
    ]
